### ISSUE TITLE
Константы нужно выносить из компонентов и функций

### ISSUE THREAD

**Issue by AeShevch** [faceless49/nbc#1]
https://github.com/faceless49/nbc/blob/f85b376e7430acca3dd8dcd3b4694183d4a88c35/pages/index.tsx#L25
https://github.com/faceless49/nbc/blob/f85b376e7430acca3dd8dcd3b4694183d4a88c35/pages/index.tsx#L67
https://github.com/faceless49/nbc/blob/f85b376e7430acca3dd8dcd3b4694183d4a88c35/pages/index.tsx#L75
А тут вы ещё и передаёте потом эту константу как пропс, зачем?

**Comment by faceless49** [comment]
Fix.
