### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by AeShevch** [faceless49/nbc#3]
https://github.com/faceless49/nbc/blob/f85b376e7430acca3dd8dcd3b4694183d4a88c35/pages/index.tsx#L28-L39
https://github.com/faceless49/nbc/blob/f85b376e7430acca3dd8dcd3b4694183d4a88c35/pages/index.tsx#L69-L70

Обращения к api следует оформить отдельным модулем, и использовать через него.
Что-то вроде: `await api.getImages();`

**Comment by AeShevch** [comment]
https://github.com/faceless49/nbc/blob/f85b376e7430acca3dd8dcd3b4694183d4a88c35/pages/photo/%5Bid%5D.tsx#L46-L50

**Comment by faceless49** [comment]
Fix.
