### ISSUE TITLE
antd

### ISSUE THREAD

**Issue by AeShevch** [faceless49/nbc#5]
Детальная страница вообще никак не оформлена, в анте столько компонентов, почему было бы не использовать, если не было желания оформлять самостоятельно.

https://github.com/faceless49/nbc/blob/f85b376e7430acca3dd8dcd3b4694183d4a88c35/pages/index.tsx#L2
Почему стили для анта подключаете только на одной странице, а не глобально а app.tsx?

**Comment by faceless49** [comment]
Fix.
