### ISSUE TITLE
Семантика

### ISSUE THREAD

**Issue by AeShevch** [faceless49/nbc#9]
https://github.com/faceless49/nbc/blob/f85b376e7430acca3dd8dcd3b4694183d4a88c35/components/Gallery/index.tsx#L20-L21

Тег `<a>` здесь не имеет текстового содержимого, а соответственно, непонятно куда ведёт ссылка – необходимо указывать атрибуты `title/aria-label`

Вообще весь этот блок, это набор ссылок, а значит ничто иное как навигация, а соответственно было бы правильно обернуть его в тег `<nav>`

Детальная страница отлично подходит под тег `article`, комментарии следовало оформить, например, списком

**Comment by faceless49** [comment]
Fix
